project_name: tripaille
strict: true
module:
    base_module: tripal
    instance_cls: "<class 'tripal.TripalInstance'>"
    instance_func: TripalInstance
    instance_args:
        - "http://localhost:8500/tripal/"
        - "admin"
        - "changeme"

    ignore:
        top_attrs:
            - 'tripal_url'
            - 'username'
            - 'password'
            - 'auth_login'
            - 'auth_password'
            - 'version'
        funcs:
            - get
            - post

documentation: |
    Tripaille is a set of wrappers for accessing Tripal. Each utility is implemented as
    a subcommand of ``tripaille``. This section of the documentation
    describes these commands.
