language: python
python:
- '2.7'
- '3.5'
script:
- pip install -U pip setuptools
- pip install -U flake8
- flake8 tripal --ignore=E501 --exclude=scripts/
- python setup.py install
deploy:
  provider: pypi
  user: abretaud
  password:
    secure: ozrSUU6Jbh0n+nh0UX5EpzWZdlOfMGC5I4SaCS7C0v2At/x/YZ32fW0N2+p2eJwyx6yfv8jELihjCZf7tagTrsUYqKwYxbWwLVNRT0m+SJgt160EkLK7cYJrSv1PdBDjcmqEDGG7J/6h+qRLM3jVo6YgKNL3AWE0YIgqfOOMF0Anl6A4+cfqXJUlfDienxdbfPGjLeAmzqeZ59rUoAyVFZRW2YokLM9DwLA+0kipqLlmZHOiFXJ9SJ0YMqyaswOeRplUmpGUqTnjQ0IuPQyWx0coxTQ8DdivpDLAANNOgQgBA9zcy/+UuJDeMy4lBEpEk1mCSKVrU3zODzzbF48J7llDV412PbFueyrCx7D6NLsdKC+I/IhI+Rf67A8fY3/siz/OMThErL89qJp8W67s18zhXKcG7+GeiypMoNCK7gWef5CfgV6Zsh4nV31yIZjXg0/RTQzf2rmmI36NkbVKAN+TYmH6VJWs6x5SFklmKPt70lypwfSEao5f+kEJz2XwOf2judkZwcOU67vyptz0sG/Z+QxlKOEogbRy13eV4qgqSyZEa1c8nAaIS80pPKbXU/MYWBRSaYY8FtYiITemDGlcO0fyny0F4XRQDrN6cAr7zus7GtHbsZNXwsN9g4imq8Th7b8L6G+xwFbo8jtvjuo07Ef7J8Hf3lUEzXoxQw0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: galaxy-genome-annotation/python-tripal
