sudo: required
language: python

services:
  - docker

python:
  - '2.7'

jobs:
  include:
    - stage: lint
      install:
        - pip install -U flake8 flake8-import-order
      script:
        - flake8 tripal test --ignore=E501 --exclude=scripts/
    - stage: test  # Python 2.7 + tripal 2
      env: TRIPAL_VERSION=2
      python: '2.7'
      install:
        - pip install -U pip setuptools nose chado
        - python setup.py install
        - export TRIPAILLE_GLOBAL_CONFIG_PATH=`pwd`/test-data/tripal_v$TRIPAL_VERSION/tripaille.yml
        - export CHAKIN_GLOBAL_CONFIG_PATH=`pwd`/test-data/tripal_v$TRIPAL_VERSION/chakin.yml
        - sudo service postgresql stop
        - cd test-data/tripal_v$TRIPAL_VERSION/
        - docker-compose up -d
        - cd ../../
        - sleep 360 # Wait for the containers to be ready
        - docker-compose logs
      script:
        - python setup.py nosetests --tests test.tripal_v$TRIPAL_VERSION
    - stage: test  # Python 3.5 + tripal 2
      env: TRIPAL_VERSION=2
      python: '3.5'
      install:
        - pip install -U pip setuptools nose chado
        - python setup.py install
        - export TRIPAILLE_GLOBAL_CONFIG_PATH=`pwd`/test-data/tripal_v$TRIPAL_VERSION/tripaille.yml
        - export CHAKIN_GLOBAL_CONFIG_PATH=`pwd`/test-data/tripal_v$TRIPAL_VERSION/chakin.yml
        - sudo service postgresql stop
        - cd test-data/tripal_v$TRIPAL_VERSION/
        - docker-compose up -d
        - cd ../../
        - sleep 360 # Wait for the container to be ready
        - docker-compose logs
      script:
        - python setup.py nosetests --tests test.tripal_v$TRIPAL_VERSION
    - stage: test  # Python 2.7 + tripal 3
      env: TRIPAL_VERSION=3
      python: '2.7'
      install:
        - pip install -U pip setuptools nose chado
        - python setup.py install
        - export TRIPAILLE_GLOBAL_CONFIG_PATH=`pwd`/test-data/tripal_v$TRIPAL_VERSION/tripaille.yml
        - export CHAKIN_GLOBAL_CONFIG_PATH=`pwd`/test-data/tripal_v$TRIPAL_VERSION/chakin.yml
        - sudo service postgresql stop
        - cd test-data/tripal_v$TRIPAL_VERSION/
        - docker-compose up -d
        - cd ../../
        - while sleep 9m; do echo "[TRAVIS] Still running..."; done &
        - sleep 900 # Wait for the containers to be ready
        - docker-compose logs
      script:
        - python setup.py nosetests --tests test.tripal_v$TRIPAL_VERSION
    - stage: test  # Python 3.5 + tripal 3
      env: TRIPAL_VERSION=3
      python: '3.5'
      install:
        - pip install -U pip setuptools nose chado
        - python setup.py install
        - export TRIPAILLE_GLOBAL_CONFIG_PATH=`pwd`/test-data/tripal_v$TRIPAL_VERSION/tripaille.yml
        - export CHAKIN_GLOBAL_CONFIG_PATH=`pwd`/test-data/tripal_v$TRIPAL_VERSION/chakin.yml
        - sudo service postgresql stop
        - cd test-data/tripal_v$TRIPAL_VERSION/
        - docker-compose up -d
        - cd ../../
        - while sleep 9m; do echo "[TRAVIS] Still running..."; done &
        - sleep 900 # Wait for the container to be ready
        - docker-compose logs
      script:
        - python setup.py nosetests --tests test.tripal_v$TRIPAL_VERSION
    - stage: deploy
      install: skip
      script: echo "Deploying to Pypi"
      deploy:
        provider: pypi
        user: abretaud
        password:
          secure: ozrSUU6Jbh0n+nh0UX5EpzWZdlOfMGC5I4SaCS7C0v2At/x/YZ32fW0N2+p2eJwyx6yfv8jELihjCZf7tagTrsUYqKwYxbWwLVNRT0m+SJgt160EkLK7cYJrSv1PdBDjcmqEDGG7J/6h+qRLM3jVo6YgKNL3AWE0YIgqfOOMF0Anl6A4+cfqXJUlfDienxdbfPGjLeAmzqeZ59rUoAyVFZRW2YokLM9DwLA+0kipqLlmZHOiFXJ9SJ0YMqyaswOeRplUmpGUqTnjQ0IuPQyWx0coxTQ8DdivpDLAANNOgQgBA9zcy/+UuJDeMy4lBEpEk1mCSKVrU3zODzzbF48J7llDV412PbFueyrCx7D6NLsdKC+I/IhI+Rf67A8fY3/siz/OMThErL89qJp8W67s18zhXKcG7+GeiypMoNCK7gWef5CfgV6Zsh4nV31yIZjXg0/RTQzf2rmmI36NkbVKAN+TYmH6VJWs6x5SFklmKPt70lypwfSEao5f+kEJz2XwOf2judkZwcOU67vyptz0sG/Z+QxlKOEogbRy13eV4qgqSyZEa1c8nAaIS80pPKbXU/MYWBRSaYY8FtYiITemDGlcO0fyny0F4XRQDrN6cAr7zus7GtHbsZNXwsN9g4imq8Th7b8L6G+xwFbo8jtvjuo07Ef7J8Hf3lUEzXoxQw0=
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: galaxy-genome-annotation/python-tripal
